import type { SecretRule } from "./types.js";

export const GITLEAKS_VERSION = "v8.30.1";

export const GENERATED_SECRET_RULES: readonly SecretRule[] = [
	{
		id: "anthropic-admin-api-key",
		sourceId: "anthropic-admin-api-key",
		regexSource:
			"\\b(sk-ant-admin01-[a-zA-Z0-9_\\-]{93}AA)(?:[\\x60'\"\\s;]|\\\\[nr]|$)",
		caseInsensitive: false,
		secretGroup: 1,
		allowlistRegexSources: [],
	},
	{
		id: "anthropic-api-key",
		sourceId: "anthropic-api-key",
		regexSource:
			"\\b(sk-ant-api03-[a-zA-Z0-9_\\-]{93}AA)(?:[\\x60'\"\\s;]|\\\\[nr]|$)",
		caseInsensitive: false,
		secretGroup: 1,
		allowlistRegexSources: [],
	},
	{
		id: "aws-access-key-id",
		sourceId: "aws-access-token",
		regexSource: "\\b((?:A3T[A-Z0-9]|AKIA|ASIA|ABIA|ACCA)[A-Z2-7]{16})\\b",
		caseInsensitive: false,
		secretGroup: 1,
		allowlistRegexSources: [".+EXAMPLE$"],
	},
	{
		id: "google-api-key",
		sourceId: "gcp-api-key",
		regexSource: "\\b(AIza[\\w-]{35})(?:[\\x60'\"\\s;]|\\\\[nr]|$)",
		caseInsensitive: false,
		secretGroup: 1,
		allowlistRegexSources: [
			"AIzaSyabcdefghijklmnopqrstuvwxyz1234567",
			"AIzaSyAnLA7NfeLquW1tJFpx_eQCxoX-oo6YyIs",
			"AIzaSyCkEhVjf3pduRDt6d1yKOMitrUEke8agEM",
			"AIzaSyDMAScliyLx7F0NPDEJi1QmyCgHIAODrlU",
			"AIzaSyD3asb-2pEZVqMkmL6M9N6nHZRR_znhrh0",
			"AIzayDNSXIbFmlXbIE6mCzDLQAqITYefhixbX4A",
			"AIzaSyAdOS2zB6NCsk1pCdZ4-P6GBdi_UUPwX7c",
			"AIzaSyASWm6HmTMdYWpgMnjRBjxcQ9CKctWmLd4",
			"AIzaSyANUvH9H9BsUccjsu2pCmEkOPjjaXeDQgY",
			"AIzaSyA5_iVawFQ8ABuTZNUdcwERLJv_a_p4wtM",
			"AIzaSyA4UrcGxgwQFTfaI3no3t7Lt1sjmdnP5sQ",
			"AIzaSyDSb51JiIcB6OJpwwMicseKRhhrOq1cS7g",
			"AIzaSyBF2RrAIm4a0mO64EShQfqfd2AFnzAvvuU",
			"AIzaSyBcE-OOIbhjyR83gm4r2MFCu4MJmprNXsw",
			"AIzaSyB8qGxt4ec15vitgn44duC5ucxaOi4FmqE",
			"AIzaSyA8vmApnrHNFE0bApF4hoZ11srVL_n0nvY",
		],
	},
	{
		id: "github-app-token",
		sourceId: "github-app-token",
		regexSource: "(?:ghu|ghs)_[0-9a-zA-Z]{36}",
		caseInsensitive: false,
		secretGroup: 0,
		allowlistRegexSources: [],
	},
	{
		id: "github-fine-grained-pat",
		sourceId: "github-fine-grained-pat",
		regexSource: "github_pat_\\w{82}",
		caseInsensitive: false,
		secretGroup: 0,
		allowlistRegexSources: [],
	},
	{
		id: "github-oauth",
		sourceId: "github-oauth",
		regexSource: "gho_[0-9a-zA-Z]{36}",
		caseInsensitive: false,
		secretGroup: 0,
		allowlistRegexSources: [],
	},
	{
		id: "github-pat",
		sourceId: "github-pat",
		regexSource: "ghp_[0-9a-zA-Z]{36}",
		caseInsensitive: false,
		secretGroup: 0,
		allowlistRegexSources: [],
	},
	{
		id: "gitlab-pat",
		sourceId: "gitlab-pat",
		regexSource: "glpat-[\\w-]{20}",
		caseInsensitive: false,
		secretGroup: 0,
		allowlistRegexSources: [],
	},
	{
		id: "npm-access-token",
		sourceId: "npm-access-token",
		regexSource: "\\b(npm_[a-z0-9]{36})(?:[\\x60'\"\\s;]|\\\\[nr]|$)",
		caseInsensitive: true,
		secretGroup: 1,
		allowlistRegexSources: [],
	},
	{
		id: "openai-api-key",
		sourceId: "openai-api-key",
		regexSource:
			"\\b(sk-(?:proj|svcacct|admin)-(?:[A-Za-z0-9_-]{74}|[A-Za-z0-9_-]{58})T3BlbkFJ(?:[A-Za-z0-9_-]{74}|[A-Za-z0-9_-]{58})\\b|sk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20})(?:[\\x60'\"\\s;]|\\\\[nr]|$)",
		caseInsensitive: false,
		secretGroup: 1,
		allowlistRegexSources: [],
	},
	// Local regex override applied from scripts/ruleset-config.ts.
	{
		id: "private-key",
		sourceId: "private-key",
		regexSource:
			"-----BEGIN[ A-Z0-9_-]{0,100}PRIVATE KEY(?: BLOCK)?-----(?:(?:[A-Za-z0-9+/=\\s-]|\\\\[nr]){64,}?KEY(?: BLOCK)?-----|(?:[A-Za-z0-9+/=\\s-]|\\\\[nr])+\\\\?$)",
		caseInsensitive: true,
		secretGroup: 0,
		allowlistRegexSources: [],
	},
	{
		id: "sendgrid-api-token",
		sourceId: "sendgrid-api-token",
		regexSource:
			"\\b(SG\\.[a-zA-Z0-9=_\\-\\.]{66})(?:[\\x60'\"\\s;]|\\\\[nr]|$)",
		caseInsensitive: false,
		secretGroup: 1,
		allowlistRegexSources: [],
	},
	{
		id: "slack-bot-token",
		sourceId: "slack-bot-token",
		regexSource: "xoxb-[0-9]{10,13}-[0-9]{10,13}[a-zA-Z0-9-]*",
		caseInsensitive: false,
		secretGroup: 0,
		allowlistRegexSources: [],
	},
	{
		id: "slack-user-token",
		sourceId: "slack-user-token",
		regexSource: "xox[pe](?:-[0-9]{10,13}){3}-[a-zA-Z0-9-]{28,34}",
		caseInsensitive: false,
		secretGroup: 0,
		allowlistRegexSources: [],
	},
	{
		id: "slack-webhook-url",
		sourceId: "slack-webhook-url",
		regexSource:
			"(?:https?://)?hooks.slack.com/(?:services|workflows|triggers)/[A-Za-z0-9+/]{43,56}",
		caseInsensitive: false,
		secretGroup: 0,
		allowlistRegexSources: [],
	},
	{
		id: "stripe-access-token",
		sourceId: "stripe-access-token",
		regexSource:
			"\\b((?:sk|rk)_(?:test|live|prod)_[a-zA-Z0-9]{10,99})(?:[\\x60'\"\\s;]|\\\\[nr]|$)",
		caseInsensitive: false,
		secretGroup: 1,
		allowlistRegexSources: [],
	},
	{
		id: "twilio-api-key",
		sourceId: "twilio-api-key",
		regexSource: "SK[0-9a-fA-F]{32}",
		caseInsensitive: false,
		secretGroup: 0,
		allowlistRegexSources: [],
	},
];
